[package]
name = "dice_fsharp"
version = "0.0.1"
edition = "2021"
workspace = "../"

[dependencies]
fable_library_rust = { path = "../../polyglot/lib/rust/fable/fable_modules/fable-library-rust", optional = true, default-features = false }
rand = { version = "~0.8", optional = true }

[features]
wasm = ["fable_library_rust"]
default = ["fable_library_rust/default", "dep:rand"]

[[bin]]
name = "dice_fsharp"
path = "dice_fsharp.rs"

[lib]
path = "dice_wasm_fsharp.rs"
