param(
    $fast,
    $ScriptDir = $PSScriptRoot
)
Set-Location $ScriptDir
$ErrorActionPreference = "Stop"
. ../deps/polyglot/scripts/core.ps1


# npx -y tailwindcss -i input.css -o target/tailwind.css

if (!$fast) {
    . $(Search-Command bunx) --bun ssl-serve --ssl dist
} else {
    # The native app (src/main.rs, regenerated by build.ps1) served by trunk from this directory.
    . ../deps/polyglot/deps/spiral/lib/spiral/lib.ps1
    $rustBindgen = [regex]::Match((Get-Content ../Cargo.lock -Raw), '(?m)^name = "wasm-bindgen"\r?\nversion = "([^"]+)"').Groups[1].Value
    { trunk serve --dist="$(GetTargetDir dice_ui)/trunk-serve" --no-sri } | Invoke-Block -EnvironmentVariables @{ "TRUNK_TOOLS_WASM_BINDGEN" = $rustBindgen }
}
